baseURL = 'https://making-of-a-maker.com'
languageCode = 'en-us'
title = 'Making of a Maker'
theme = 'PaperMod'

# Enable SEO.
[params]
env = "production"

[params.homeInfoParams]
Title = "Welcome"
Content = """
👋 Welcome to the **Making of a Maker** blog!

-

- May name is James. I'm a 33 year old guy learning to build with modern low-code development tools.

- 

- I am not a software developer by background. But I am interested and see building applications as a way to scratch my creative itch.

- 

- I have spent longer than I care like to admit lurking on forums like [Indie Hackers](https://www.indiehackers.com/) or reading stories about successful side projects on [Medium](https://medium.com/).

- 

- I've decided it's time to stop observing and take action. Here is where I will share my progress.

- 

- If you are interested in building your own low-code side project, **subscribe below**. I'd love to be in touch with other aspiring makers. 

"""
